catalogMode: prefer
ignoreWorkspaceRootCheck: true
shamefullyHoist: true

catalogs:
  dev:
    "@soybeanjs/cli": ^1.6.1
    "@types/minimist": ^1.2.5
    "@types/node": ^25.5.0
    "@types/prompts": ^2.4.9
    "lint-staged": ^16.4.0
    "oxfmt":  ^0.41.0
    "oxlint":  ^1.56.0
    "simple-git-hooks": ^2.13.1
    "tsdown": ^0.21.4
    "tsx": ^4.21.0
    "typescript": ^5.9.3
  prod:
    consola: ^3.4.2
    kolorist: ^1.8.0
    minimist: ^1.2.8
    prompts: ^2.4.2
